name: build-publish-slf4j-klogging

on:
  workflow_dispatch:

jobs:

  build-slf4j-klogging:
    name: Build and test Klogging SLF4J provider
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: 40D4E7C6
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
      TERM: xterm-256color
      KLOGGING_MIN_LOG_LEVEL: WARN # Reduce noise in test output

    permissions:
      contents: write # Required to be able to publish releases, see https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents
      checks: write # Required to write test reports.
      statuses: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Check out everything including tags

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew :slf4j-klogging:assemble

      - name: Run tests
        run: ./gradlew :slf4j-klogging:check

      - name: Code coverage
        run: ./gradlew :slf4j-klogging:koverHtmlReport

      - name: Check test output existence
        id: check_test_output
        uses: andstor/file-existence-action@v3
        with:
          files: ./slf4j-klogging/build/test-results/test/*.xml
        if: success() || failure()

      - name: Test report
        uses: dorny/test-reporter@v2
        with:
          name: Kotest report
          path: ./slf4j-klogging/build/test-results/test/*.xml
          reporter: java-junit
        if: steps.check_test_output.outputs.files_exists == 'true'

      - name: Publish Klogging SLF4J provider to Maven Central
        run: ./gradlew :slf4j-klogging:publishJvmPublicationToMavenCentralRepository
