name: build-publish-jdk-platform-klogging

on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - gradle/**
      - jdk-platform-klogging/**
      - "!jdk-platform-klogging/README.md"
  workflow_dispatch:
  workflow_run:
    workflows: [build-publish-klogging]
    types: [completed]

jobs:

  build-jdk-platform-klogging:
    name: Build and test Klogging implementation for JDK Platform Logging
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: 40D4E7C6
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
      TERM: xterm-256color
      KLOGGING_MIN_LOG_LEVEL: WARN # Reduce noise in test output

    permissions:
      contents: write # Required to be able to publish releases, see https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents
      checks: write # Required to write test reports.
      statuses: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Check out everything including tags

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew :jdk-platform-klogging:assemble

      - name: Run tests
        run: ./gradlew :jdk-platform-klogging:check

      - name: Code coverage
        run: ./gradlew :jdk-platform-klogging:koverHtmlReport

      - name: Check test output existence
        id: check_test_output
        uses: andstor/file-existence-action@v3
        with:
          files: ./jdk-platform-klogging/build/test-results/test/*.xml
        if: success() || failure()

      - name: Test report
        uses: dorny/test-reporter@v2
        with:
          name: Kotest report
          path: ./jdk-platform-klogging/build/test-results/test/*.xml
          reporter: java-junit
        if: steps.check_test_output.outputs.files_exists == 'true'

      - name: Publish Klogging JPL implementation to Maven Central
        run: ./gradlew :jdk-platform-klogging:publishJvmPublicationToMavenCentralRepository
