name: build-publish-klogging

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - .github/**
      - gradle/**
      - klogging/**
  workflow_dispatch:

jobs:

  build-klogging:
    name: Build and test Klogging library
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_ID: 40D4E7C6
      OSSRH_USERNAME: mjstrasser
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      TERM: xterm-256color
      KLOGGING_MIN_LOG_LEVEL: WARN # Reduce noise in test output

    permissions:
      contents: write # Required to be able to publish releases, see https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents
      checks: write # Required to write test reports.
      statuses: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Check out everything including tags

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew :klogging:assemble

      - name: Run tests
        run: ./gradlew :klogging:jvmCheck :klogging:jvmTest # jvmCheck does not seem to run jvmTest

      - name: Code coverage
        run: ./gradlew :klogging:koverHtmlReport

      - name: Check test output existence
        id: check_test_output
        uses: andstor/file-existence-action@v3
        with:
          files: ./klogging/build/test-results/test/*.xml
        if: success() || failure()

      - name: Test report
        uses: dorny/test-reporter@v1
        with:
          name: Kotest report
          path: ./klogging/build/test-results/test/*.xml
          reporter: java-junit
        if: steps.check_test_output.outputs.files_exists == 'true'

      - name: Publish Klogging snapshot
        run: ./gradlew :klogging:publishAllPublicationsToSnapshotsRepository
        if: github.repository == 'klogging/klogging' && github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')

      - name: Publish Klogging release
        run: ./gradlew :klogging:publishAllPublicationToReleaseRepository
        if: github.repository == 'klogging/klogging' && startsWith(github.ref, 'refs/tags/') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')

  build-klogging-apple:
    name: Build apple versions of Klogging library
    runs-on: macos-latest
    needs: build-klogging
    env:
      SIGNING_KEY_ID: 40D4E7C6
      OSSRH_USERNAME: mjstrasser
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      TERM: xterm-256color
      KLOGGING_MIN_LOG_LEVEL: WARN # Reduce noise in test output

    permissions:
      contents: write # Required to be able to publish releases, see https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents
      checks: write # Required to write test reports.
      statuses: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Check out everything including tags

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish Klogging snapshot
        run: ./gradlew :klogging:publishIosArm64PublicationToSnapshotsRepository :klogging:publishIosX64PublicationToSnapshotsRepository :klogging:publishIosSimulatorArm64PublicationToSnapshotsRepository
        if: github.repository == 'klogging/klogging' && github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')

      - name: Publish Klogging release
        run: ./gradlew :klogging:publishIosArm64PublicationToReleaseRepository :klogging:publishIosX64PublicationToReleaseRepository :klogging:publishIosSimulatorArm64PublicationToReleaseRepository
        if: github.repository == 'klogging/klogging' && startsWith(github.ref, 'refs/tags/') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
