name: publish-spring-boot-starter

on:
  workflow_dispatch:
  workflow_call:

jobs:

  build-slf4j-klogging:
    name: Publish Spring Boot starter POM
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: 40D4E7C6
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
      TERM: xterm-256color

    permissions:
      contents: write # Required to be able to publish releases, see https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents
      checks: write # Required to write test reports.
      statuses: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Check out everything including tags

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Publish Spring Boot starter to Maven Central
        run: ./gradlew :klogging-spring-boot-starter:publishAllPublicationsToMavenCentralRepository --no-configuration-cache
